apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "patroni.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "patroni.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "patroni.fullname" . }}
      labels:
        app: {{ template "patroni.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "patroni.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.pgVersion }}
        - name: PGVERSION
          value: "{{ .Values.pgVersion }}"
        {{- end }}
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: password-superuser
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: password-admin
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: password-standby
        {{- if .Values.kubernetes.dcs.enable }}
        - name: DCS_ENABLE_KUBERNETES_API
          value: "true"
        - name: KUBERNETES_LABELS
          value: {{ (printf "{ \"app\": \"%s\", \"release\": \"%s\" }" (include "patroni.name" .) .Release.Name) | quote }}
        - name: KUBERNETES_SCOPE_LABEL
          value: "app"
        {{- end }}
        {{- if .Values.kubernetes.configmaps.enable }}
        - name: KUBERNETES_USE_CONFIGMAPS
          value: "true"
        {{- end }}
        {{- if .Values.etcd.enable }}
        {{- if .Values.etcd.deployChart }}
        - name: ETCD_DISCOVERY_DOMAIN
          value: {{default (printf "%s-etcd" .Release.Name | trunc 63) .Values.etcd.discovery }}
        {{- else }}
        - name: ETCD_HOST
          value: {{ .Values.etcd.host | quote }}
        {{- end }}
        {{- else if .Values.zookeeper.enable }}
        {{- if .Values.zookeeper.deployChart }}
        - name: ZOOKEEPER_HOSTS
          value: {{(printf "'%s-zookeeper-headless:2181'" .Release.Name | trunc 63)}}
        {{- else }}
        - name: ZOOKEEPER_HOSTS
          value: {{ .Values.zookeeper.hosts | quote }}
        {{- end }}
        {{- end }}
        - name: SCOPE
          value: {{ template "patroni.fullname" . }}
        {{- if .Values.walE.enable }}
        - name: USE_WALE
          value: {{ .Values.walE.enable | quote }}
        {{- if .Values.walE.scheduleCronJob }}
        - name: BACKUP_SCHEDULE
          value: {{ .Values.walE.scheduleCronJob | quote}}
        {{- end }}
        {{- if .Values.walE.retainBackups }}
        - name: BACKUP_NUM_TO_RETAIN
          value: {{ .Values.walE.retainBackups | quote}}
        {{- end }}
        {{- if .Values.walE.s3.enable }}
        - name: WAL_S3_BUCKET
          value: {{ .Values.walE.s3.bucket | quote }}
        {{- if .Values.walE.s3.endpoint }}
        - name: WALE_S3_ENDPOINT
          value: {{ .Values.walE.s3.waleEndpoint | quote }}i
        {{- end }}
        {{- if .Values.walE.s3.accessKey }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.walE.s3.accessKey | quote }}
        {{- end }}
        {{- if .Values.walE.s3.secretKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: aws-secret-key
        {{- end }}
        {{else if .Values.walE.gcs.enable }}
        - name: WAL_GCS_BUCKET
          value: {{ .Values.walE.gcs.bucket | quote }}
        {{- if .Values.walE.gcs.credentialsSecret }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/{{.Values.walE.gcs.credentialsSecret}}.json"
        {{- end }}
        {{else if .Values.walE.swift.enable }}
        - name: WAL_SWIFT_BUCKET
          value: {{ .Values.walE.swift.bucket | quote }}
        - name: SWIFT_AUTHURL
          value: {{ .Values.walE.swift.authUrl | quote }}
        {{- if .Values.walE.swift.tenant }}
        - name: SWIFT_TENANT
          value: {{ .Values.walE.swift.tenant | quote }}
        {{- end }}
        - name: SWIFT_USER
          value: {{ .Values.walE.swift.user | quote }}
        - name: SWIFT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: swift-password
        {{- if .Values.walE.swift.authVersion }}
        - name: SWIFT_AUTH_VERSION
          value: {{ .Values.walE.swift.authVersion | quote }}
        {{- end }}
        {{- if .Values.walE.swift.endpointType }}
        - name: SWIFT_ENDPOINT_TYPE
          value: {{ .Values.walE.swift.endpointType | quote }}
        {{- end }}
        {{else if .Values.walE.file.enable }}
        - name: WALE_FILE_PREFIX
          value: {{ .Values.walE.file.path | quote }}
        {{- end }}
        {{- if .Values.walE.backupThresholdMegabytes }}
        - name: WALE_BACKUP_THRESHOLD_MEGABYTES
          value: {{ .Values.walE.backupThresholdMegabytes | quote }}
        {{- end }}
        {{- if .Values.walE.backupThresholdPercentage }}
        - name: WALE_BACKUP_THRESHOLD_PERCENTAGE
          value: {{ .Values.walE.backupThresholdPercentage | quote }}
        {{- end }}
        {{- else }}
        - name: USE_WALE
          value: ""
        {{- end }}
        - name: PGROOT
          value: "{{ .Values.persistentVolume.mountPath }}/pgroot"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8008
        - containerPort: 5432
        volumeMounts:
        - name: storage-volume
          mountPath: "{{ .Values.persistentVolume.mountPath }}"
          subPath: "{{ .Values.persistentVolume.subPath }}"
        - mountPath: /etc/patroni
          name: patroni-config
          readOnly: true
        {{- if .Values.walE.enable }}
        {{- if .Values.walE.gcs.credentialsSecret }}
        - name: {{ .Values.walE.gcs.credentialsSecret  }}
          mountPath: /etc/credentials
          readOnly: true
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
{{ tpl .Values.affinity . | indent 8 }}
      volumes:
      - name: patroni-config
        secret:
          secretName: {{ template "patroni.fullname" . }}
      {{- if .Values.walE.enable }}
      {{- if .Values.walE.gcs.credentialsSecret }}
      - name: {{ .Values.walE.gcs.credentialsSecret }}
        secret:
          secretName: {{ .Values.walE.gcs.credentialsSecret }}
      {{- end }}
      {{- end }}
      {{- if not .Values.persistentVolume.enabled }}
      - name: storage-volume
        emptyDir: {}
      {{- end }}
  {{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
        annotations:
        {{- if .Values.persistentVolume.annotations }}
{{ toYaml .Values.persistentVolume.annotations | indent 8 }}
        {{- end }}
        labels:
          app: {{ template "patroni.name" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 8 }}
        resources:
          requests:
            storage: "{{ .Values.persistentVolume.size }}"
      {{- if .Values.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.persistentVolume.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistentVolume.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
